nodeLinker: node-modules

npmScopes:
  magnus-strategy:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://europe-npm.pkg.dev/magnus-strategy/registry/"
    npmRegistryServer: "https://europe-npm.pkg.dev/magnus-strategy/registry/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-gcp-auth.cjs
    spec: "https://github.com/AndyClausen/yarn-plugin-gcp-auth/releases/latest/download/plugin-gcp-auth.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
