name: Continuous integration

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [ opened, synchronize ]

jobs:
    check:
        name: Code check
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup bun
                uses: oven-sh/setup-bun@v1

            -   name: Install dependencies
                run:  bun install --frozen-lockfile

            -   name: Lint
                run: bun lint

            -   name: Type check
                run: bun typecheck

    test:
        name: Test
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup bun
                uses: oven-sh/setup-bun@v1

            -   name: Install dependencies
                run:  bun install --frozen-lockfile

            -   name: Test
                run: bun test

    release:
        name: Release
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        needs: [ check, test ]
        permissions:
            contents: 'write'
            id-token: 'write'
            issues: 'write'
            pull-requests: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup bun
                uses: oven-sh/setup-bun@v1

            -   name: Install dependencies
                run:  bun install --frozen-lockfile

            -   name: Create Release Pull Request or Publish to npm
                uses: changesets/action@v1
                with:
                    publish: bun run publish
                    version: bun run version
                    commit: 'chore: release'
                    title: 'chore: release'
                env:
                    GITHUB_TOKEN: ${{ secrets.HEXATOOL_GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.HEXATOOL_NPM_TOKEN }}
