name: Continuous integration

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
        types: [ opened, synchronize ]

jobs:
    check:
        name: Code check
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup bun
                uses: oven-sh/setup-bun@v1

            -   name: Install dependencies
                run: bun install

            -   name: Lint
                run: bun lint

            -   name: Type check
                run: bun typecheck

    release:
        name: Release
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        needs: [ check ]
        permissions:
            contents: 'write'
            id-token: 'write'
            issues: 'write'
            pull-requests: 'write'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup bun
                uses: oven-sh/setup-bun@v1

            -   name: Install dependencies
                run: bun install

            -   name: Configure Git User
                run: |
                    git config --global user.email "github-actions@magnus-strategy.com"
                    git config --global user.name "$GITHUB_ACTOR"

            -   name: Create Release Pull Request or Publish to npm
                uses: changesets/action@v1
                with:
                    publish: bun publish
                    version: bun version
                    commit: 'chore: release'
                    title: 'chore: release'
                    setupGitUser: false
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
